# Generated by Django 4.1.6 on 2023-02-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="name"
            ),
        ),
    ]
