# Generated by Django 4.1.6 on 2023-02-17 19:38

import profiles.models
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=profiles.models.profile_image_file_path,
                validators=[profiles.validators.validate_image_size],
            ),
        ),
    ]
